"""empty message

Revision ID: 116ca33732ef
Revises: b80e7967aeb6
Create Date: 2020-09-10 02:11:41.942055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '116ca33732ef'
down_revision = 'b80e7967aeb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('account_type', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('language', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'language')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'account_type')
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
