"""empty message

Revision ID: 4234cf460270
Revises: 96006b827e5f
Create Date: 2020-09-15 00:39:36.416193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4234cf460270'
down_revision = '96006b827e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'url')
    # ### end Alembic commands ###
