"""empty message

Revision ID: 5ac2cba24eb2
Revises: ec4d027376c8
Create Date: 2020-09-10 16:12:05.775147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac2cba24eb2'
down_revision = 'ec4d027376c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
