"""empty message

Revision ID: e5781c0f6c27
Revises: 995d7400adfa
Create Date: 2020-10-12 20:21:31.235661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5781c0f6c27'
down_revision = '995d7400adfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_upload', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_upload')
    # ### end Alembic commands ###
