"""empty message

Revision ID: e5a523e67d40
Revises: 1d74078e77a9
Create Date: 2020-09-24 12:56:35.834307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a523e67d40'
down_revision = '1d74078e77a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('title', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'title')
    # ### end Alembic commands ###
